### PR TITLE
add support for undump

### PR DESCRIPTION
**Pull request by cfwen**
undump is the reverse operation of dump: all variables in a dump file will be loaded and set() will be called to update the pp file or generate a registry file

### CODE REVIEW

**Comment by cfwen** [comment]
@sibradzic would you consider merge this MR?

**Comment by sibradzic** [comment]
@cfwen sorry, I somehow missed this, completely m(_ _)m

**Review by sibradzic — CHANGES_REQUESTED** [review]
Can you please add a note into a README & bump a version @ https://github.com/sibradzic/upp/blob/master/setup.py#L8 ?

**Comment by cfwen** [comment]
updated. I also fixed a few typos as I found them. 

Thank you for this great tool.

**Review by sibradzic — APPROVED** [review]

**Comment by sibradzic** [comment]
merged & published
Much obliged!

**Pull request merged**
